pages:
  stage: deploy
  image: rocker/r-base:latest
  before_script:
    - apt-get update -qq
    - apt-get install -t unstable software-properties-common --yes
    - add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - apt-get install -t unstable --yes libcurl4-openssl-dev libssl-dev git libmagick++-dev pandoc pandoc-citeproc
  script:
    - Rscript -e 'install.packages(c("devtools", "pkgdown", "remotes))'
    - Rscript -e 'devtools::install_dev_deps()'
    - Rscript -e 'remotes::install_gitlab("dickoa/ochathemes")'
    - Rscript -e 'pkgdown::build_site()'
  artifacts:
    paths:
    - public

